Bulkblocks and Files tests
dmwm/dbs2go pull request #37
Opened 2022-05-11 19:41 UTC by d-ylee

Added Bulkblocks POST tests for parent and child.

Implemented Files GET tests that contain block_name.

2022-05-11 21:17 UTC, vkuznet reviewed
Dennis, I'll review your PR tomorrow, but so far the only question I have is that this PR seems only address `bulkblocks.go` while we have two implementations. The only you're using here and another is concurrent implementation which you can find in `bulkblocks2.go`. The DBS server can be configured to use either one or another via `abd.ConcurrentBulkBlocks` parameter. I would expect that this PR should cover both use-case. Please let me know if you consider doing that.

2022-05-12 13:25 UTC, d-ylee commented
@vkuznet I initially did the Bulkblocks insert in order to write the files GET tests with the ranged run_num parameter. I can add on a ConcurrentBulkBlocks insert test.

2022-05-13 11:43 UTC, vkuznet requested changes
I suggest to wait on this PR merge when you'll provide similar integration tests for concurrent bulk block insert. I also put few minor comments which I want to clarify with you before the merge.

2022-05-13 11:43 UTC, vkuznet commented on dbs/bulkblocks.go
> +		// if the data string does not contain the is_file_valid field
I think we need identical block of code in `bulkblocks2.go` too

2022-05-13 11:43 UTC, vkuznet commented on test/integration_test.go
> +				/*
if this block of code is no longer required could you please remove it

2022-05-13 11:43 UTC, vkuznet commented on test/integration_test.go
> +				/*
I'm not sure why you remove POST method check, could you please explain this

2022-05-17 12:05 UTC, vkuznet requested changes
Dennis, I think having  separate `EndpointTestCase` in `getConcurrentBulkBlocksTestTable` and `getBulkBlocksTestTable ` functions is overkill since they suppose to do the same thing. Instead I suggest to define a single helper function, e.g. `testCaseBulkBlocks` where you can pass concurrent argument and it will create proper `EndpointTestCase` structure. Then, you may use this structure within `getConcurrentBulkBlocksTestTable` and `getBulkBlocksTestTable ` functions . For instance, 
```
func testCaseBulkBlocks(t *testing.T, concurrent bool) EndpointTestCase {
      blockName := []string{TestData.ParentStepchainBlock}
      if concurrent {
           blockName := []string{TestData.ParentStepchainBlock+"2"}
      }
      return EndpointTestCase{
           ....
           concurrentBulkBlocks: concurrent
            ....
                params : urlValues{"block_name": blockName}
      }
}
```
and, then you'll simplify `getConcurrentBulkBlocksTestTable` and `getBulkBlocksTestTable ` functions to
```
func getConcurrentBulkBlocksTestTable(t *testing.T) EndpointTestCase {
     return testCaseBulkBlocks(t, true)
}
func getBulkBlocksTestTable(t *testing.T) EndpointTestCase {
      return testCaseBulkBlocks(t, false)
}
```

2022-05-17 16:12 UTC, vkuznet approved these changes

2022-05-17 16:13 UTC, merged